"""
macOS backend — Quartz + pyobjc + mss + pyautogui.

Implements docs/COMPUTER_USE.md against the macOS APIs:
- Screen capture / cursor / displays: Quartz + mss
- Input: pyautogui (which routes to CoreGraphics CGEvent under the hood)
- Window list / focus: CGWindowListCopyWindowInfo + AXRaise
- App list / launch: NSWorkspace
- Clipboard: NSPasteboard (raw, so we can read concealed-type markers)
- Permissions: AXIsProcessTrusted + CGPreflightScreenCaptureAccess

Every Quartz / AppKit symbol is imported lazily inside the method so
the module loads cleanly in tests that mock the backend out.
"""

from __future__ import annotations

import logging
import subprocess
import time
from typing import Any

from ...config import ShimConfig
from ...protocol import AppInfo, DisplayMonitor, WindowInfo
from ..backend import ClipboardReadResult, ComputerUseBackend, ScreenshotResult
from ..display import displays_to_bounds_list, displays_via_mss
from ..errors import (
    ClipboardConcealedError,
    FeatureNotSupportedError,
    InputOutOfBoundsError,
    PermissionPendingError,
)
from ..window_registry import WindowFingerprint
from ._common import (
    PASTE_THRESHOLD_CHARS,
    image_to_base64,
    in_any_rect,
    normalize_displays_for_error,
)

logger = logging.getLogger(__name__)


CONCEALED_PB_TYPES = {
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "org.nspasteboard.TransientType",
}


class MacOSBackend(ComputerUseBackend):
    def __init__(self, config: ShimConfig) -> None:
        super().__init__(config)
        self._clipboard_enabled = getattr(config, "enable_clipboard", False)
        self._clipboard_read_foreign = getattr(config, "enable_clipboard_read_foreign", False)

    # ── Capability advertisement ──────────────────────────────────────

    def coarse_features(self) -> list[str]:
        feats = ["screenshot", "input", "windows", "apps", "permissions"]
        if self._clipboard_enabled:
            feats.append("clipboard")
        return feats

    def features(self) -> list[str]:
        feats = [
            "screenshot.region",
            "screenshot.window",
            "input.click.modifiers",
            "input.click.button",
            "input.drag.path",
            "input.key.hold",
            "input.mouse.down_up",
            "input.scroll.amount",
            "input.wait",
            "cursor.position",
            "display.info",
            "window.list",
            "window.focus",
            "app.list",
            "app.launch",
            "permissions.check",
        ]
        if self._clipboard_enabled:
            feats.extend(["clipboard.read", "clipboard.write"])
        return feats

    # ── Screenshot ───────────────────────────────────────────────────

    def screenshot(
        self,
        *,
        monitor: int = 0,
        quality: int = 75,
        region: tuple[int, int, int, int] | None = None,
        window_id: str | None = None,
        format: str = "jpeg",
        include_cursor: bool = True,
    ) -> ScreenshotResult:
        if region is not None and window_id is not None:
            raise FeatureNotSupportedError(
                "screenshot.region+window",
                reason="region and window_id are mutually exclusive",
            )

        try:
            import mss  # type: ignore[import-not-found]
            from PIL import Image  # type: ignore[import-untyped]
        except ImportError as exc:
            raise FeatureNotSupportedError(
                "screenshot", reason=f"mss/Pillow missing: {exc}"
            ) from exc

        if window_id is not None:
            # Resolve native handle via Quartz (CGWindowListCreateImage).
            return self._screenshot_window(
                window_id, quality=quality, format=format, include_cursor=include_cursor
            )

        displays = self.display_info()
        if not displays:
            raise FeatureNotSupportedError("screenshot", reason="no displays detected")
        if monitor < 0 or monitor >= len(displays):
            monitor = 0
        target = displays[monitor]

        try:
            with mss.mss() as sct:
                # mss monitor 0 = stitched; +1 to address an individual display.
                mon = sct.monitors[monitor + 1]
                if region is not None:
                    rx1, ry1, rx2, ry2 = region
                    # Clip the region into the target monitor and convert to
                    # mss's per-monitor-relative space.
                    mx, my, mw, mh = mon["left"], mon["top"], mon["width"], mon["height"]
                    # region is display-global; clamp to this monitor's rect.
                    cx1 = max(rx1, mx)
                    cy1 = max(ry1, my)
                    cx2 = min(rx2, mx + mw)
                    cy2 = min(ry2, my + mh)
                    if cx2 <= cx1 or cy2 <= cy1:
                        raise FeatureNotSupportedError(
                            "screenshot.region",
                            reason=f"region {region} does not intersect monitor {monitor}",
                        )
                    capture = {
                        "left": cx1,
                        "top": cy1,
                        "width": cx2 - cx1,
                        "height": cy2 - cy1,
                    }
                    raw = sct.grab(capture)
                    origin = (cx1, cy1)
                else:
                    raw = sct.grab(mon)
                    origin = (mon["left"], mon["top"])
                img = Image.frombytes("RGB", raw.size, raw.bgra, "raw", "BGRX")
        except FeatureNotSupportedError:
            raise
        except Exception as exc:
            raise self._screen_recording_or_other(exc)

        if include_cursor:
            try:
                self._composite_cursor(img, origin)
            except Exception:
                logger.debug("cursor composite failed", exc_info=True)

        img_bytes, mime = image_to_base64(img, format=format, quality=quality)
        # NB: image_to_base64 returns bytes; the dispatcher b64-encodes.
        return ScreenshotResult(
            image_bytes=img_bytes,
            mime_type=mime,
            width=img.width,
            height=img.height,
            monitor=target.index,
            region=region,
            display_scale=target.scale,
            logical_size=target.logical_size,
            origin=origin,
            display_id=target.index,
        )

    def _composite_cursor(self, img: Any, origin: tuple[int, int]) -> None:
        """Overlay the system cursor at its current location.

        mss doesn't draw the cursor for us on macOS. We get the
        location from Quartz NSEvent and stamp a tiny black arrow —
        good enough for the model to see "there's the cursor" without
        the per-OS cursor-image fetch dance.
        """
        try:
            from PIL import ImageDraw  # type: ignore[import-untyped]
            from Quartz import NSEvent  # type: ignore[import-not-found]
        except ImportError:
            return
        try:
            loc = NSEvent.mouseLocation()
            # macOS mouseLocation is bottom-left origin in screen points;
            # we want top-left in the same coord space as our crop.
            primary = self._primary_display_size()
            if primary is None:
                return
            x = int(loc.x) - origin[0]
            y = int(primary[1] - loc.y) - origin[1]
            if 0 <= x < img.width and 0 <= y < img.height:
                d = ImageDraw.Draw(img)
                d.polygon(
                    [(x, y), (x + 12, y + 4), (x + 5, y + 5), (x + 4, y + 12)],
                    fill=(0, 0, 0),
                )
        except Exception:
            return

    def _primary_display_size(self) -> tuple[int, int] | None:
        try:
            from Quartz import CGDisplayBounds, CGMainDisplayID  # type: ignore[import-not-found]

            bounds = CGDisplayBounds(CGMainDisplayID())
            return int(bounds.size.width), int(bounds.size.height)
        except Exception:
            return None

    def _screen_recording_or_other(self, exc: Exception) -> Exception:
        """Map mss/CG screen-capture failures to PermissionPendingError
        when the failure is a TCC denial (the message text is the
        cheapest signal we have without re-importing Quartz)."""
        msg = str(exc).lower()
        if "screen" in msg and ("permission" in msg or "denied" in msg or "tcc" in msg):
            return PermissionPendingError(
                "screen_recording",
                "darwin",
                hint="System Settings → Privacy & Security → Screen Recording",
            )
        return exc

    def _screenshot_window(
        self,
        window_id: str,
        *,
        quality: int,
        format: str,
        include_cursor: bool,
    ) -> ScreenshotResult:
        try:
            from PIL import Image  # type: ignore[import-untyped]
            from Quartz import (  # type: ignore[import-not-found]
                CGRectNull,
                CGWindowListCreateImage,
                kCGWindowImageDefault,
                kCGWindowListOptionIncludingWindow,
            )
        except ImportError as exc:
            raise FeatureNotSupportedError("screenshot.window", reason=str(exc)) from exc

        entry = self.window_registry.verify(window_id, self._live_fingerprint)
        cg_window_id = int(entry.native_handle)
        rect = CGRectNull
        ref = CGWindowListCreateImage(
            rect, kCGWindowListOptionIncludingWindow, cg_window_id, kCGWindowImageDefault
        )
        if ref is None:
            raise PermissionPendingError(
                "screen_recording",
                "darwin",
                hint="Window capture failed; grant Screen Recording in System Settings.",
            )
        # Convert CGImage → PIL via a pragmatic png round-trip through
        # Cocoa NSBitmapImageRep (ships in pyobjc; simpler than the
        # CGDataProvider dance).
        try:
            from Cocoa import (  # type: ignore[import-not-found]
                NSBitmapImageRep,
                NSPNGFileType,
            )

            rep = NSBitmapImageRep.alloc().initWithCGImage_(ref)
            png_data = rep.representationUsingType_properties_(NSPNGFileType, {})
            bytes_data = bytes(png_data)
            from io import BytesIO

            img = Image.open(BytesIO(bytes_data))
        except Exception as exc:
            raise FeatureNotSupportedError(
                "screenshot.window", reason=f"CGImage conversion failed: {exc}"
            ) from exc

        bounds = entry.extra.get("bounds", (0, 0, img.width, img.height))
        origin = (int(bounds[0]), int(bounds[1]))
        img_bytes, mime = image_to_base64(img, format=format, quality=quality)
        return ScreenshotResult(
            image_bytes=img_bytes,
            mime_type=mime,
            width=img.width,
            height=img.height,
            monitor=int(entry.extra.get("monitor", 0)),
            region=None,
            display_scale=1.0,
            logical_size=(img.width, img.height),
            origin=origin,
            display_id=int(entry.extra.get("monitor", 0)),
        )

    # ── Input ────────────────────────────────────────────────────────

    def input_action(
        self,
        action: str,
        *,
        coordinate: tuple[int, int] | None = None,
        text: str | None = None,
        key: str | None = None,
        direction: str | None = None,
        clicks: int | None = None,
        button: str | None = None,
        modifiers: list[str] | None = None,
        scroll_amount: int | None = None,
        scroll_direction: str | None = None,
        duration_ms: int | None = None,
        path: list[tuple[int, int]] | None = None,
        paste: bool = False,
        preserve_clipboard: bool = False,
    ) -> None:
        if action == "wait":
            ms = max(0, min(int(duration_ms or 0), 5000))
            time.sleep(ms / 1000.0)
            return

        # Bounds check (Q1) — applies to any action that takes a coordinate.
        if coordinate is not None:
            self._check_bounds(coordinate)
        if path:
            for pt in path:
                self._check_bounds(pt)

        if not self._ax_trusted():
            raise PermissionPendingError(
                "accessibility",
                "darwin",
                hint="System Settings → Privacy & Security → Accessibility",
            )

        try:
            import pyautogui  # type: ignore[import-untyped]
        except ImportError as exc:
            raise FeatureNotSupportedError("input", reason=str(exc)) from exc

        pyautogui.FAILSAFE = True

        if action == "mouse_move" and coordinate:
            pyautogui.moveTo(coordinate[0], coordinate[1])
            return
        if action in ("left_click", "right_click", "double_click", "middle_click", "triple_click"):
            self._click(action, coordinate, modifiers)
            return
        if action == "mouse_down" and coordinate:
            pyautogui.mouseDown(coordinate[0], coordinate[1], button=button or "left")
            return
        if action == "mouse_up" and coordinate:
            pyautogui.mouseUp(coordinate[0], coordinate[1], button=button or "left")
            return
        if action == "drag" and path:
            btn = button or "left"
            pyautogui.moveTo(path[0][0], path[0][1])
            pyautogui.mouseDown(button=btn)
            try:
                for pt in path[1:]:
                    pyautogui.moveTo(pt[0], pt[1], duration=0.01)
            finally:
                pyautogui.mouseUp(button=btn)
            return
        if action == "type" and text is not None:
            self._type(text, paste=paste, preserve_clipboard=preserve_clipboard)
            return
        if action == "key" and key:
            pyautogui.hotkey(*self._chord(key))
            return
        if action == "hold_key" and key:
            duration = max(0.0, min((duration_ms or 0) / 1000.0, 5.0))
            for k in self._chord(key):
                pyautogui.keyDown(k)
            try:
                time.sleep(duration)
            finally:
                for k in reversed(self._chord(key)):
                    pyautogui.keyUp(k)
            return
        if action == "scroll":
            amount = scroll_amount if scroll_amount is not None else (clicks or 3)
            d = scroll_direction or direction or "down"
            sign = 1 if d in ("up", "right") else -1
            if coordinate:
                if d in ("left", "right"):
                    pyautogui.hscroll(sign * amount, x=coordinate[0], y=coordinate[1])
                else:
                    pyautogui.scroll(sign * amount, x=coordinate[0], y=coordinate[1])
            else:
                pyautogui.scroll(sign * amount)
            return
        raise FeatureNotSupportedError(action, reason=f"unknown action {action!r}")

    def _click(
        self,
        action: str,
        coordinate: tuple[int, int] | None,
        modifiers: list[str] | None,
    ) -> None:
        import pyautogui  # type: ignore[import-untyped]

        if coordinate is None:
            raise FeatureNotSupportedError(action, reason="coordinate is required")
        mods = list(modifiers or [])
        for m in mods:
            pyautogui.keyDown(self._modifier(m))
        try:
            if action == "left_click":
                pyautogui.click(coordinate[0], coordinate[1])
            elif action == "right_click":
                pyautogui.rightClick(coordinate[0], coordinate[1])
            elif action == "double_click":
                pyautogui.doubleClick(coordinate[0], coordinate[1])
            elif action == "middle_click":
                pyautogui.middleClick(coordinate[0], coordinate[1])
            elif action == "triple_click":
                pyautogui.tripleClick(coordinate[0], coordinate[1])
        finally:
            for m in reversed(mods):
                pyautogui.keyUp(self._modifier(m))

    @staticmethod
    def _modifier(name: str) -> str:
        return {"super": "command", "ctrl": "ctrl", "alt": "option", "shift": "shift"}.get(
            name, name
        )

    @staticmethod
    def _chord(key: str) -> list[str]:
        return [k.strip().lower() for k in key.split("+") if k.strip()]

    def _check_bounds(self, coordinate: tuple[int, int]) -> None:
        displays = self.display_info()
        bounds = displays_to_bounds_list(displays)
        if not in_any_rect(coordinate, bounds):
            raise InputOutOfBoundsError(coordinate, normalize_displays_for_error(bounds))

    # ── Cursor / display ─────────────────────────────────────────────

    def cursor_position(self) -> tuple[int, int, int]:
        try:
            from Quartz import NSEvent  # type: ignore[import-not-found]
        except ImportError as exc:
            raise FeatureNotSupportedError("cursor.position", reason=str(exc)) from exc
        loc = NSEvent.mouseLocation()
        primary = self._primary_display_size() or (0, 0)
        x = int(loc.x)
        y = int(primary[1] - loc.y)
        # find which monitor contains (x, y)
        displays = self.display_info()
        idx = 0
        for d in displays:
            ox, oy = d.origin
            w, h = d.physical_size
            if ox <= x < ox + w and oy <= y < oy + h:
                idx = d.index
                break
        return x, y, idx

    def display_info(self) -> list[DisplayMonitor]:
        # Quartz first (HiDPI scale); mss fallback.
        try:
            from Quartz import (  # type: ignore[import-not-found]
                CGDisplayBounds,
                CGDisplayPixelsHigh,
                CGDisplayPixelsWide,
                CGGetActiveDisplayList,
                CGMainDisplayID,
            )

            max_displays = 16
            err, ids, _ = CGGetActiveDisplayList(max_displays, None, None)
            if err != 0 or not ids:
                raise RuntimeError("CGGetActiveDisplayList failed")
            main = CGMainDisplayID()
            out: list[DisplayMonitor] = []
            for i, did in enumerate(ids):
                bounds = CGDisplayBounds(did)
                logical_w = int(bounds.size.width)
                logical_h = int(bounds.size.height)
                physical_w = int(CGDisplayPixelsWide(did))
                physical_h = int(CGDisplayPixelsHigh(did))
                scale = round(physical_w / logical_w, 2) if logical_w else 1.0
                out.append(
                    DisplayMonitor(
                        index=i,
                        primary=(did == main),
                        physical_size=(physical_w, physical_h),
                        logical_size=(logical_w, logical_h),
                        scale=scale,
                        origin=(int(bounds.origin.x), int(bounds.origin.y)),
                    )
                )
            return out
        except Exception:
            ms = displays_via_mss()
            if ms:
                return ms
            raise FeatureNotSupportedError("display.info", reason="no display backend")

    # ── Windows ──────────────────────────────────────────────────────

    def window_list(
        self,
        *,
        app_bundle_id: str | None = None,
        include_minimized: bool = False,
        include_offscreen: bool = False,
    ) -> list[WindowInfo]:
        try:
            from Quartz import (  # type: ignore[import-not-found]
                CGWindowListCopyWindowInfo,
                kCGNullWindowID,
                kCGWindowListExcludeDesktopElements,
                kCGWindowListOptionOnScreenOnly,
            )
        except ImportError as exc:
            raise FeatureNotSupportedError("window.list", reason=str(exc)) from exc

        opts = kCGWindowListExcludeDesktopElements
        if not include_offscreen:
            opts |= kCGWindowListOptionOnScreenOnly
        info = CGWindowListCopyWindowInfo(opts, kCGNullWindowID)
        # Clear stale mappings — the Q2 contract says window_ids are
        # only valid for one LIST/USE cycle. We don't wipe (HELLO does
        # that) but we also don't carry stale entries forward.
        self.window_registry.clear()
        out: list[WindowInfo] = []
        focused_pid = self._focused_pid()
        for entry in info:
            try:
                cg_id = int(entry.get("kCGWindowNumber", 0))
                pid = int(entry.get("kCGWindowOwnerPID", 0))
                if pid == 0 or cg_id == 0:
                    continue
                owner_name = entry.get("kCGWindowOwnerName") or ""
                title = entry.get("kCGWindowName") or ""
                bnds = entry.get("kCGWindowBounds") or {}
                x = int(bnds.get("X", 0))
                y = int(bnds.get("Y", 0))
                w = int(bnds.get("Width", 0))
                h = int(bnds.get("Height", 0))
                bundle = self._bundle_for_pid(pid)
                if app_bundle_id and bundle != app_bundle_id:
                    continue
                fp = WindowFingerprint(
                    pid=pid,
                    class_name=owner_name,
                    creation_timestamp=None,
                )
                wid = self.window_registry.mint(
                    cg_id,
                    fp,
                    extra={
                        "bounds": (x, y, x + w, y + h),
                        "monitor": 0,
                    },
                )
                out.append(
                    WindowInfo(
                        window_id=wid,
                        pid=pid,
                        app_name=str(owner_name),
                        app_bundle_id=bundle,
                        title=str(title) if title else None,
                        bounds=(x, y, x + w, y + h),
                        monitor=0,
                        is_focused=(pid == focused_pid),
                        is_minimized=False,
                        is_fullscreen=False,
                    )
                )
            except Exception:
                logger.debug("skipping unparseable window entry", exc_info=True)
        return out

    def _live_fingerprint(self, cg_window_id: Any) -> WindowFingerprint | None:
        try:
            from Quartz import (  # type: ignore[import-not-found]
                CGWindowListCopyWindowInfo,
                kCGWindowListOptionIncludingWindow,
            )

            info = CGWindowListCopyWindowInfo(kCGWindowListOptionIncludingWindow, int(cg_window_id))
            if not info:
                return None
            entry = info[0]
            return WindowFingerprint(
                pid=int(entry.get("kCGWindowOwnerPID", 0)),
                class_name=entry.get("kCGWindowOwnerName") or "",
                creation_timestamp=None,
            )
        except Exception:
            return None

    def _focused_pid(self) -> int | None:
        try:
            from AppKit import NSWorkspace  # type: ignore[import-not-found]

            front = NSWorkspace.sharedWorkspace().frontmostApplication()
            if front is None:
                return None
            return int(front.processIdentifier())
        except Exception:
            return None

    def _bundle_for_pid(self, pid: int) -> str | None:
        try:
            from AppKit import NSRunningApplication  # type: ignore[import-not-found]

            app = NSRunningApplication.runningApplicationWithProcessIdentifier_(pid)
            if app is None:
                return None
            return str(app.bundleIdentifier() or "") or None
        except Exception:
            return None

    def window_focus(self, window_id: str, *, raise_: bool = True) -> None:
        entry = self.window_registry.verify(window_id, self._live_fingerprint)
        if not self._ax_trusted():
            raise PermissionPendingError("accessibility", "darwin")
        try:
            from AppKit import NSRunningApplication  # type: ignore[import-not-found]
        except ImportError as exc:
            raise FeatureNotSupportedError("window.focus", reason=str(exc)) from exc
        live = self._live_fingerprint(entry.native_handle)
        if live is None or live.pid == 0:
            from ..errors import WindowStaleError

            raise WindowStaleError(window_id)
        app = NSRunningApplication.runningApplicationWithProcessIdentifier_(live.pid)
        if app is None:
            from ..errors import WindowStaleError

            raise WindowStaleError(window_id)
        # NSApplicationActivateAllWindows = 1; activateIgnoringOtherApps=YES.
        app.activateWithOptions_(1)

    # ── Apps ─────────────────────────────────────────────────────────

    def app_list(self, *, include_background: bool = False) -> list[AppInfo]:
        try:
            from AppKit import NSWorkspace  # type: ignore[import-not-found]
        except ImportError as exc:
            raise FeatureNotSupportedError("app.list", reason=str(exc)) from exc
        out: list[AppInfo] = []
        for app in NSWorkspace.sharedWorkspace().runningApplications():
            try:
                # 0 = regular (dock-visible), 1 = accessory, 2 = prohibited
                policy = int(app.activationPolicy())
                if not include_background and policy != 0:
                    continue
                out.append(
                    AppInfo(
                        pid=int(app.processIdentifier()),
                        name=str(app.localizedName() or ""),
                        bundle_id=str(app.bundleIdentifier() or "") or None,
                        executable_path=(
                            str(app.executableURL().path()) if app.executableURL() else None
                        ),
                        is_frontmost=bool(app.isActive()),
                        window_count=0,  # NSRunningApplication doesn't expose this
                    )
                )
            except Exception:
                continue
        return out

    def app_launch(
        self,
        *,
        bundle_id: str | None = None,
        executable_path: str | None = None,
        args: list[str] | None = None,
        activate: bool = True,
    ) -> int:
        # Prefer NSWorkspace.openApplication for bundle-id launches; fall
        # back to `open -a` for paths, and finally raw Popen.
        try:
            from AppKit import NSWorkspace  # type: ignore[import-not-found]
        except ImportError:
            NSWorkspace = None  # type: ignore[assignment]
        if bundle_id and NSWorkspace is not None:
            try:
                ws = NSWorkspace.sharedWorkspace()
                url = ws.URLForApplicationWithBundleIdentifier_(bundle_id)
                if url is None:
                    raise FeatureNotSupportedError(
                        "app.launch", reason=f"bundle {bundle_id!r} not installed"
                    )
                # Use the synchronous open variant — async needs a config block.
                ok = ws.openURL_(url)
                if not ok:
                    raise FeatureNotSupportedError(
                        "app.launch", reason=f"failed to launch {bundle_id!r}"
                    )
                # Resolve pid via NSRunningApplication scan.
                for _ in range(20):
                    pid = self._pid_for_bundle(bundle_id)
                    if pid:
                        return pid
                    time.sleep(0.05)
                return 0
            except FeatureNotSupportedError:
                raise
            except Exception as exc:
                raise FeatureNotSupportedError("app.launch", reason=str(exc)) from exc
        if executable_path:
            proc = subprocess.Popen(
                [executable_path, *(args or [])],
                start_new_session=True,
            )
            return proc.pid
        raise FeatureNotSupportedError(
            "app.launch", reason="either bundle_id or executable_path is required"
        )

    def _pid_for_bundle(self, bundle_id: str) -> int | None:
        try:
            from AppKit import NSRunningApplication  # type: ignore[import-not-found]

            for app in NSRunningApplication.runningApplicationsWithBundleIdentifier_(bundle_id):
                return int(app.processIdentifier())
        except Exception:
            return None
        return None

    # ── Clipboard ────────────────────────────────────────────────────

    def clipboard_read(self, *, format: str = "text") -> ClipboardReadResult:
        if not self._clipboard_enabled:
            raise FeatureNotSupportedError("clipboard.read", reason="--enable-clipboard not set")
        if format != "text":
            raise FeatureNotSupportedError(
                "clipboard.read",
                reason=f"format {format!r} not supported in v1",
            )
        text, seq = self._read_pasteboard_text()
        # Concealed-marker check first.
        markers = self._read_pasteboard_types()
        for c in CONCEALED_PB_TYPES:
            if c in markers:
                raise ClipboardConcealedError(
                    "concealed_type",
                    marker=c,
                )

        if self._clipboard_read_foreign:
            content = text or ""
            return ClipboardReadResult(
                format="text", content=content, size_bytes=len(content.encode("utf-8"))
            )

        # Default (writeback-only) — must match an in-window record.
        record = self.clipboard_writeback.check(live_content=text, live_sequence=seq)
        if record is None:
            snap = self.clipboard_writeback.snapshot()
            if snap is None:
                raise ClipboardConcealedError("writeback_only")
            age = snap.age()
            if age > self.clipboard_writeback.window_seconds:
                raise ClipboardConcealedError("writeback_only", writeback_age_seconds=age)
            raise ClipboardConcealedError("writeback_overwritten")
        content = text or ""
        return ClipboardReadResult(
            format="text", content=content, size_bytes=len(content.encode("utf-8"))
        )

    def clipboard_write(self, *, format: str = "text", content: str) -> None:
        if not self._clipboard_enabled:
            raise FeatureNotSupportedError("clipboard.write", reason="--enable-clipboard not set")
        if format != "text":
            raise FeatureNotSupportedError(
                "clipboard.write", reason=f"format {format!r} not supported in v1"
            )
        seq = self._write_pasteboard_text(content)
        self.clipboard_writeback.record_write(content, sequence=seq)

    def _pasteboard(self) -> Any | None:
        try:
            from AppKit import NSPasteboard  # type: ignore[import-not-found]

            return NSPasteboard.generalPasteboard()
        except ImportError:
            return None

    def _read_pasteboard_text(self) -> tuple[str | None, int | None]:
        pb = self._pasteboard()
        if pb is None:
            return None, None
        try:
            from AppKit import NSPasteboardTypeString  # type: ignore[import-not-found]

            text = pb.stringForType_(NSPasteboardTypeString)
            return (str(text) if text is not None else None), int(pb.changeCount())
        except Exception:
            return None, None

    def _write_pasteboard_text(self, content: str) -> int | None:
        pb = self._pasteboard()
        if pb is None:
            return None
        try:
            from AppKit import NSPasteboardTypeString  # type: ignore[import-not-found]

            pb.clearContents()
            pb.setString_forType_(content, NSPasteboardTypeString)
            return int(pb.changeCount())
        except Exception:
            return None

    def _read_pasteboard_types(self) -> list[str]:
        pb = self._pasteboard()
        if pb is None:
            return []
        try:
            types = pb.types() or []
            return [str(t) for t in types]
        except Exception:
            return []

    def _type(self, text: str, *, paste: bool, preserve_clipboard: bool) -> None:
        import pyautogui  # type: ignore[import-untyped]

        if paste and len(text) >= PASTE_THRESHOLD_CHARS and self._clipboard_enabled:
            self._do_paste(text, preserve_clipboard=preserve_clipboard)
            return
        pyautogui.write(text, interval=0.02)

    def _do_paste(self, text: str, *, preserve_clipboard: bool) -> None:
        import pyautogui  # type: ignore[import-untyped]

        snapshot: tuple[str | None, int | None] | None = None
        if preserve_clipboard:
            snapshot = self._read_pasteboard_text()
        self._write_pasteboard_text(text)
        # Re-record writeback so the inner read sees us as the writer.
        self.clipboard_writeback.record_write(text)
        pyautogui.hotkey("command", "v")
        if preserve_clipboard and snapshot is not None:
            previous, prev_seq = snapshot
            time.sleep(0.05)  # let the paste consume the clipboard
            current, current_seq = self._read_pasteboard_text()
            # Skip restore if changeCount advanced past our written
            # value (means user copied during the paste).
            if previous is not None and prev_seq is not None and current_seq is not None:
                # We wrote once after snapshot → seq advanced by 1.
                # Anything beyond that means a third party wrote since.
                if current_seq > prev_seq + 1:
                    return
                self._write_pasteboard_text(previous)
                self.clipboard_writeback.record_write(previous)

    # ── Permissions ──────────────────────────────────────────────────

    def permissions_check(self, permissions: list[str]) -> dict[str, str]:
        out: dict[str, str] = {}
        for p in permissions:
            if p == "accessibility":
                out[p] = "granted" if self._ax_trusted() else "denied"
            elif p == "screen_recording":
                out[p] = "granted" if self._screen_capture_allowed() else "denied"
            elif p == "input_monitoring":
                # No public API short of a probe-and-catch; we conservatively
                # say "unknown" rather than guess.
                out[p] = "unknown"
            else:
                out[p] = "not_applicable"
        return out

    def _ax_trusted(self) -> bool:
        try:
            from ApplicationServices import (  # type: ignore[import-not-found]
                AXIsProcessTrusted,
            )

            return bool(AXIsProcessTrusted())
        except ImportError:
            return False

    def _screen_capture_allowed(self) -> bool:
        try:
            from Quartz import (  # type: ignore[import-not-found]
                CGPreflightScreenCaptureAccess,
            )

            return bool(CGPreflightScreenCaptureAccess())
        except ImportError:
            return False


__all__ = ["MacOSBackend"]
